// Generated by CoffeeScript 1.7.1
(function() {
  var a, book, c, chapter, fullList, i, quote, quoteIndex, sections, users, _i, _j, _k, _len, _len1, _ref;

  book = [
    {
      title: 'Design',
      desc: '学习最实用的设计法则，\n在 Sketch 和 Framer 中进行原型设计。',
      chapters: ['从感觉开始', '设计驱动开发', '如何激发灵感', '设计 iOS App', '三个最常用的设计语言', '交互设计']
    }, {
      title: 'Code',
      desc: '学习 Swift 和 iOS，\n掌握最实用的开发技巧与工具',
      chapters: ['Basic Swift Knowlege', 'iOS Animations', 'Facebook Pop', 'Motion Graphic', 'Git', 'UICollectionView', 'Custom Navgiation Transaction', 'Custom UILabel and UIButton', 'UIWebView', 'Core Data', 'UICollectionView Layout', 'Cocoapods & Crashlystics']
    }, {
      title: 'Market',
      desc: '掌握产品营销的方法，\n把产品推向市场',
      chapters: ['本质', '产品定位', '营销的方法', '文案']
    }
  ];

  users = [
    {
      name: 'Jonathan Ive',
      bio: 'Designer at Apple',
      avatar: './img/jony.jpg',
      say: 'I can code the system for Apple Watch by myself!'
    }, {
      name: 'Louie Mantia',
      bio: 'Designer at Parakeet',
      avatar: './img/mantia.jpg',
      say: 'This book is fucking awesome!'
    }, {
      name: 'Ray',
      bio: 'Artist at Catch Inc',
      avatar: './img/ray.jpg',
      say: 'Thanks to @kevinzhow I can Finally bring my idea into real! '
    }
  ];

  for (_i = 0, _len = book.length; _i < _len; _i++) {
    c = book[_i];
    chapter = $('<div>', {
      "class": 'chapter'
    });
    chapter.append($('<h1>', {
      text: c.title
    }));
    chapter.append($('<pre>', {
      text: c.desc
    }));
    sections = $('<ul>', {
      "class": 'sections'
    });
    for (i = _j = 0; _j <= 5; i = ++_j) {
      if (c.chapters[i] !== void 0) {
        sections.append($('<li>', {
          text: c.chapters[i]
        }));
      }
    }
    chapter.append(sections);
    $('.chapters').append(chapter);
    if (c.chapters.length > 6) {
      fullList = $('<ul>', {
        "class": 'drawer'
      });
      _ref = c.chapters;
      for (_k = 0, _len1 = _ref.length; _k < _len1; _k++) {
        a = _ref[_k];
        fullList.append($('<li>', {
          text: a
        }));
      }
      chapter.append(fullList);
      sections.append($('<span>', {
        text: 'Show All'
      }).click(function() {
        return $(fullList).fadeIn(200);
      }));
      $(fullList).mouseleave(function() {
        return $(fullList).fadeOut(200);
      });
      $(fullList).tap(function() {
        return $(fullList).fadeOut(200);
      });
    }
  }

  quote = function(index) {
    var user;
    user = users[index];
    return $('.quotes .bubble').animate({
      scale: 0.8,
      opacity: 0.2
    }, 100, 'ease-out', function() {
      $('.quotes .bubble .avatar').attr('src', user.avatar);
      $('.quotes .bubble .say').html('"' + user.say + '"');
      $('.quotes .bubble .name').html(user.name);
      $('.quotes .bubble .name').append($('<span>', {
        "class": 'bio',
        text: user.bio
      }));
      return $('.quotes .bubble').animate({
        scale: 1,
        opacity: 1
      }, 250, 'ease-out');
    });
  };

  quote(0);

  quoteIndex = 0;

  $('.ctrl .left').click(function() {
    if (quoteIndex > 0) {
      return quote(quoteIndex -= 1);
    } else {
      return quote(quoteIndex = users.length - 1);
    }
  });

  $('.ctrl .right').click(function() {
    if (quoteIndex < users.length - 1) {
      return quote(quoteIndex += 1);
    } else {
      return quote(quoteIndex = 0);
    }
  });

}).call(this);
